server:
  port: 7073
spring:
  config: 
     import: optional:configserver:http://localhost:8888
  application:
    name: JRTP701-ElgibilityDeteminationService
 
eureka:
   client:
      service-url:
          default-zone: http://localhost:8761/eureka
   